# Generated by Django 5.2.8 on 2025-11-17 08:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='닉네임')),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='레벨')),
                ('tier', models.CharField(choices=[('BRONZE', '브론즈'), ('SILVER', '실버'), ('GOLD', '골드'), ('PLATINUM', '플래티넘'), ('DIAMOND', '다이아몬드'), ('MASTER', '마스터'), ('GRANDMASTER', '그랜드마스터')], max_length=20, verbose_name='티어')),
                ('ranking_score', models.IntegerField(default=0, verbose_name='랭킹 점수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '게임 유저',
                'verbose_name_plural': '게임 유저들',
                'ordering': ['-ranking_score'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='아이템 이름')),
                ('item_type', models.CharField(choices=[('WEAPON', '무기'), ('ARMOR', '방어구'), ('ACCESSORY', '악세서리'), ('CONSUMABLE', '소모품')], max_length=20, verbose_name='아이템 타입')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('price', models.IntegerField(default=0, verbose_name='가격')),
            ],
            options={
                'verbose_name': '아이템',
                'verbose_name_plural': '아이템',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='스킬 이름')),
                ('skill_type', models.CharField(choices=[('ACTIVE', '액티브'), ('PASSIVE', '패시브'), ('ULTIMATE', '궁극기')], max_length=20, verbose_name='스킬 타입')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('cooldown', models.IntegerField(default=0, verbose_name='쿨다운(초)')),
            ],
            options={
                'verbose_name': '스킬',
                'verbose_name_plural': '스킬',
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_games', models.IntegerField(default=0, verbose_name='총 게임 수')),
                ('wins', models.IntegerField(default=0, verbose_name='승리')),
                ('losses', models.IntegerField(default=0, verbose_name='패배')),
                ('win_rate', models.FloatField(default=0.0, verbose_name='승률')),
                ('play_time', models.IntegerField(default=0, verbose_name='플레이 시간(분)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='stats.gameuser')),
            ],
            options={
                'verbose_name': '플레이어 통계',
                'verbose_name_plural': '플레이어 통계',
            },
        ),
    ]
