# Generated by Django 5.2.8 on 2025-11-18 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_count', models.IntegerField(default=0, verbose_name='사용 횟수')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='마지막 사용')),
            ],
            options={
                'verbose_name': '아이템 사용 기록',
                'verbose_name_plural': '아이템 사용 기록',
            },
        ),
        migrations.CreateModel(
            name='SkillUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_count', models.IntegerField(default=0, verbose_name='사용 횟수')),
                ('last_used', models.DateTimeField(auto_now=True, verbose_name='마지막 사용')),
            ],
            options={
                'verbose_name': '스킬 사용 기록',
                'verbose_name_plural': '스킬 사용 기록',
            },
        ),
        migrations.AddIndex(
            model_name='gameuser',
            index=models.Index(fields=['-ranking_score'], name='stats_gameu_ranking_19f0d1_idx'),
        ),
        migrations.AddIndex(
            model_name='gameuser',
            index=models.Index(fields=['tier'], name='stats_gameu_tier_6820cd_idx'),
        ),
        migrations.AddField(
            model_name='itemusage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_usages', to='stats.item'),
        ),
        migrations.AddField(
            model_name='itemusage',
            name='player_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_usages', to='stats.playerstats'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='items',
            field=models.ManyToManyField(related_name='users', through='stats.ItemUsage', to='stats.item'),
        ),
        migrations.AddField(
            model_name='skillusage',
            name='player_stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_usages', to='stats.playerstats'),
        ),
        migrations.AddField(
            model_name='skillusage',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_usages', to='stats.skill'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='skills',
            field=models.ManyToManyField(related_name='users', through='stats.SkillUsage', to='stats.skill'),
        ),
        migrations.AddIndex(
            model_name='itemusage',
            index=models.Index(fields=['player_stats', 'usage_count'], name='stats_itemu_player__1dae3b_idx'),
        ),
        migrations.AddIndex(
            model_name='itemusage',
            index=models.Index(fields=['item', 'usage_count'], name='stats_itemu_item_id_9e590e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemusage',
            unique_together={('player_stats', 'item')},
        ),
        migrations.AddIndex(
            model_name='skillusage',
            index=models.Index(fields=['player_stats', 'usage_count'], name='stats_skill_player__2f691f_idx'),
        ),
        migrations.AddIndex(
            model_name='skillusage',
            index=models.Index(fields=['skill', 'usage_count'], name='stats_skill_skill_i_208399_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skillusage',
            unique_together={('player_stats', 'skill')},
        ),
    ]
